FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache


COPY . .

CMD ["npm","run","start"]docker run -it -p 3000:3000 cf6936766f60docker
